### ISSUE TITLE
Add formatting to page tabs to allow the user to see which tab they are on more easily - 3 points

### ISSUE THREAD

**Issue by mbasso29** [mbasso29/BestofBooks#21]
**Problem:**

As a user, I need to be able to see more easily which tab I am on so that I know which screens I can navigate to

**Acceptance Criteria:**

- Each tab should be spaced out to allow for easier readability.
- Each tab should be highlighted to clearly display which tab is currently activated.
- Styling and colors can be added in a future story.

**Comment by Super-Derek** [comment]
Feature added using site css style/ Aria and javascript. Current styles applied are for testing purposes and not permanent, to be replaced with final styling

**Comment by mbasso29** [comment]
Adding 5 points to this story due to javascript complexity
