### ISSUE TITLE
Create BestofBooks Database - 3 points

### ISSUE THREAD

**Issue by mbasso29** [mbasso29/BestofBooks#6]
**Problem:**
As a developer, I need to have a way of saving book information and user information in a database for use by the application.

**Acceptance Criteria:**

- Design a database using the information discussed in our design session. Including a user table, employee table, book table, genre table and author table.
- Create the database based on the above logical design
- Set up user DB roles and groups for users to use to login

Task list

 - [x] Design Book Database https://github.com/mbasso29/BestofBooks/milestone/1
 - [x] Create book database based on design https://github.com/mbasso29/BestofBooks/milestone/2
 - [x] Set up DB roles and groups https://github.com/mbasso29/BestofBooks/milestone/3

**Comment by Super-Derek** [comment]
Database designed in DBSchema and created in sql server. Melanie has produced a script to create database and created roles.

**Comment by mbasso29** [comment]
Adding 3 points for this story
